jina-ai/now

now/cli/__init__.py

fix: do not show init message on help args

---

now/run_backend.py
now/utils.py

This will show before-after comparison image as a pop-up.  ~~And also the print will be highlighted as shown below to attract users attention~~ Do not highlight it, it will be a distraction:
#67

fix: show overview as pop up

---

now/cloud_manager.py
now/data_loading/data_loading.py
now/deployment/flow.py
now/dialog.py
now/finetuning/finetuning.py
now/gke_deploy.py
now/hub/hub.py
now/run_all_k8s.py
now/run_backend.py
now/run_frontend.py
now/utils.py

I have added sigmap which wil handle the `SIGINT` & `SIGTERM` interruptions.
Also the `os.system['clear']` is removed as it causes deleting the terminal history which is not wanted!

fix: handle ctrl+c and remove os clear

---

now/hub/head_encoder/head_encoder.py
now/utils.py

fix: use cpu only

---

now/dialog.py
now/run_all_k8s.py
now/system_information.py

fix: use command to get context lists

---

.pre-commit-config.yaml
now/data_loading/convert_datasets_to_jpeg.py
now/data_loading/data_loading.py

Thumbnail images to (256, 256) to solve #82 and #72

feat: thumbnail images to (256, 256)

---

.github/workflows/ci.yml
.pre-commit-config.yaml
now/cloud_manager.py
now/dialog.py
now/run_all_k8s.py
requirements.txt
tests/integration/test_end_to_end.py

Test for integration end-to-end

---

now/frontend/frontend.py

feat: add slider for confidence filtering

---

requirements.txt
requirements_pip.txt

jina now is broken by the latest version of jina. Not using the latest version fixes the problem

fix: fixed jina version

---

now/frontend/deploy-frontend-docker.sh
now/frontend/frontend.py
now/frontend/requirements.txt
now/run_all_k8s.py

Added support for video streaming - Webcam. Used two different libraries, however, they fail to work when the frontend application is running on a remote server. In this scenario, the libraries fail to initialize the webcam as it needs the application to have an HTTPS URL.
For remote deployment - `Webcam` options will give error but this is allowed for now!

feat: webcam support

---

now/data_loading/build_datasets.py
now/data_loading/utils.py
now/frontend/frontend.py
now/frontend/requirements.txt
now/run_all_k8s.py

Closes #119.
Note need to rerun CI after https://github.com/jina-ai/now/pull/121 has been merged to build and push new frontend.

Feat clean text data

---

.github/workflows/ci.yml
now/data_loading/data_loading.py

if someone does not want to use music, they still have to import this library

fix: only import pydub in case of music

---

now/dialog.py
tests/integration/test_end_to_end.py

sometimes, sandbox is hanging. Therefore, we need to deactivate it for now. 
We were still not able to reproduce the issue in a deterministic way.

fix: deactivate sandbox

---

deployment/bff/requirements.txt
now/data_loading/requirements.txt
now/deployment/flow.py
now/run_all_k8s.py
requirements.txt

At the moment there is some bad log output with the progress bar where it is printed in two lines. This pr aims to fix this issue since progress is tracked when sending the request and not when receiving it.

fix: logging issue

---

.github/workflows/cd.yml
.github/workflows/ci.yml
deployment/bff/app/app.py
deployment/bff/app/v1/api.py
now/run_all_k8s.py
tests/unit/bff/test_app.py

Separate bff for different modalities

feat: add router for modalities

---

now/data_loading/data_loading.py

chore: changed wording to reduce ambiguity between DocArray and datasets

---

deployment/playground/playground.py
now/run_all_k8s.py

fix: convert tensor first

---

docs/_templates/sidebar/navigation.html

This reverts commit 282829fa0bb9ca03b2fd70066200e8c4a9a0c9bc.

Revert "docs(tracking): update external links' source (#143)"

---

now/apps/image_to_image/app.py
now/apps/image_to_text/app.py
now/apps/music_to_music/app.py
now/apps/text_to_image/app.py
now/cli/parser.py
now/constants.py
now/data_loading/data_loading.py
now/deployment/flow.py
now/finetuning/embeddings.py
now/finetuning/run_finetuning.py
now/run_backend.py
tests/unit/test_finetuning/test_music_uses_cached_hub_model.py

This PR update the music2music app in the NOW lib.

feat: add music to music app

---

now/datasource/datasource.py
now/datasource/example.py

We are planning to add more data sources in the future. Therefore, datasource should become a concept which can be easier handled and maintained

refactor: datasource init

---

README.md

updated the survey link in the readme

Fix: readme survey link

---

deployment/bff/requirements.txt
now/apps/base/flow.yml
now/apps/music_to_music/ft-flow-music.yml
now/apps/text_to_text/flow-sbert.yml
now/constants.py
now_common/flow/flow-clip.yml
now_common/flow/ft-flow-clip.yml
requirements.txt

Bump jina version in the `requirements.txt` file and also fix it in the flow.yml files

fix: update version

---

now/apps/image_to_image/app.py
now/apps/image_to_text/app.py
now/apps/text_to_image/app.py
now/apps/text_to_text/app.py
now/deployment/flow.py

before:
- got quickly stuck at 100 and then waiting
after:
- goes step by step

fix: progress bar

---

now/deployment/flow.py

larger request sizes tend to get stuck in the gateway on wolf

fix: reduce request_size

---

deployment/playground/playground.py
now/constants.py

Gifs are not rendered in the playground anymore

fix: video

---

deployment/playground/src/constants.py
deployment/playground/src/search.py
now/constants.py

There was a problem with wolf deployment. It always required the port.

fix: playground

---

deployment/playground/playground.py
deployment/playground/requirements.txt
deployment/playground/src/constants.py
deployment/playground/src/search.py
now/constants.py

To get more than 9 matches for a given query, pass `top_k` as the query param in the frontend. For example:
`http://192.168.3.20:8653/?host=grpcs://nowapi-6518949c7f.wolf.jina.ai&input_modality=text&output_modality=image&data=best-artworks&top_k=30`

Add pagination

---

deployment/bff/app/app.py
now/constants.py

At the moment, we only get a 500 back without more details. After this is merged, we get better output to investigate errors

feat: error handling in bff

---

now/apps/base/app.py
now/apps/image_to_image/app.py
now/apps/image_to_text/app.py
now/apps/text_to_image/app.py
now/constants.py
now/finetuning/settings.py
now_common/utils.py

"Finetunable datasets" is an app property from my perspective.

refactor: finetune datasets

---

tests/integration/security/test_api_key.py

The small test is much better when debugging since it just takes 1 or 2 min to execute and allows to set breakpoints within the bff

Test small test for api key

---

deployment/playground/src/search.py
now/constants.py

Fix issue reported by user here: https://jina-ai.slack.com/archives/C0169V26ATY/p1660906624476299

fix: issue reported by user

---

deployment/playground/playground.py
deployment/playground/src/search.py
now/constants.py

Catch any exception from BFF and print it in a clear format as shown in picture below:
Expanding this will show the complete stack trace -

Fix refined logging

---

deployment/bff/app/v1/routers/helper.py
now/admin/run_performance_test.py
now/admin/update_api_keys.py
now/client/__init__.py

make the calls from the client package to the bff instead directly to the flow

refactor client to bff

---

now/apps/text_to_text_and_image/app.py
now/apps/text_to_text_and_image/flow.yml
now/constants.py

Adds a static flow for text2text+image app, which contains three variables:
1. ENV.JINA_TOKEN - Authentication token for hubble
2. ENV.CLIP_ARTIFACT - Artifact ID for fine-tuned CLIP model
3. ENV.SBERT_ARTIFACT - Artifact ID for fine-tuned SBERT model

feat: add flow for text2text+image app

---

now/apps/music_to_music/demo-data-flow-music.yml
now/apps/music_to_music/ft-flow-music.yml
now/apps/text_to_text/flow-sbert.yml
now/apps/text_to_text/ft-flow-sbert.yml
now/apps/text_to_video/flow-video-clip-high-performance.yml
now/apps/text_to_video/flow-video-clip.yml
now/apps/text_to_video/ft-flow-video-clip-high-performance.yml
now/apps/text_to_video/ft-flow-video-clip.yml
now/constants.py
now_common/flow/flow-clip.yml
now_common/flow/ft-flow-clip.yml

Closes #425 by setting post processor memory usage to default

fix: reset post processor mem usage

---

now/apps/base/flow.yml
now/apps/music_to_music/demo-data-flow-music.yml
now/apps/music_to_music/ft-flow-music.yml
now/apps/text_to_text/flow-sbert.yml
now/apps/text_to_text/ft-flow-sbert.yml
now/apps/text_to_video/flow-video-clip-high-performance.yml
now/apps/text_to_video/flow-video-clip.yml
now/apps/text_to_video/ft-flow-video-clip-high-performance.yml
now/apps/text_to_video/ft-flow-video-clip.yml
now/constants.py
now_common/flow/flow-clip.yml
now_common/flow/ft-flow-clip.yml
now_common/utils.py

Fix the env var and set the retention days to 7 for non CI deployment

fix: update flow with env var

---

now/now_dataclasses.py
tests/conftest.py
tests/resources/config.json
tests/unit/test_dataclasses.py

Quick PR to add data classes because we need them for other tasks.
Will probably be refactored in the near future. 
Using `pydantic` because `dataclasses` can't load nested classes from json.

feat: add data classes

---

now_executors/ann_lite_now/executor.py
now_executors/ann_lite_now/tests/test_executor.py
now_executors/docarray_indexer/docarray_indexer_v3.py
now_executors/docarray_indexer/tests/test_integration.py

this pr allows deleting by filter conditions. It will be used by the sync job to remove old documents

feat: index delete by filter

---

now/cli/parser.py
now/finetuning/run_finetuning.py
now/run_backend.py

Fix the cli
- and also fixes the bug introduced in refactoring

fix: update cli parser

---

now/run_all_k8s.py
now/utils.py
tests/unit/apps/test_apps.py

feat: improve code coverage

---

now/apps/text_to_video/app.py
now/constants.py
tests/unit/apps/test_preprocessing.py

add more tests for pre-processing

test: preprocessing

---

docs/requirements.txt

fix: docs build

---

deployment/playground/playground.py
now/constants.py

fixes https://github.com/jina-ai/now/issues/352 and https://github.com/jina-ai/now.private/issues/107

fix: logout issue

---

now/run_all_k8s.py
now/utils.py
tests/integration/test_end_to_end.py

fix: make url more obvious

---

now/constants.py
now_common/options.py

comma separated user_emails to list of user_emails

fix: convert user emails to list

---

now/run_all_k8s.py

fix: url playground not showing

---

deployment/bff/app/v1/routers/helper.py
now/constants.py

Static CNAME entry will have `*.dev.jina.ai` as the URL. Hence, adding it while forming jina client

Fix enable static cname

---

now/constants.py
now_common/abstract_executors/NOWBaseIndexer/base_indexer.py
now_common/abstract_executors/NOWBaseIndexer/ranking.py
tests/now_executors/NOWAnnLiteIndexer/test_executor.py

get's the document where most chunks are matching. When the same number of chunks is retrieved, it compares the average score

feat: sum ranker

---

now/apps/base/app.py
now/constants.py
now_common/utils.py

Update link to the embedded dataset beacause of the recent refactor

fix: minor update

---

.github/workflows/force-deploy-examples.yml
deployment/bff/app/v1/routers/admin.py
now/constants.py
scripts/deploy_examples.py

Add an endpoint to get the status of the host.
Script calls this status to check the status and then deploy

Fix deploy example script

---

now/common/preprocess.py
now/constants.py
now/finetuning/generation_fns.py
tests/resources/text+image/config.json
tests/unit/test_finetuning/test_data_builder.py

adapt finetuner data generation test to new changes

fix: data generation test

---

now/app/text_to_text_and_image/app.py
now/common/utils.py
now/constants.py

closes https://github.com/jina-ai/now.private/issues/180

fix: retention days

---

.github/workflows/ci.yml
deployment/bff/app/v1/routers/text2text.py
deployment/bff/app/v1/routers/txt2img.py
deployment/bff/app/v1/routers/txt2video.py
deployment/playground/playground.py
deployment/playground/src/search.py
docs/user-guides/production.md
now/app/base/app.py
now/app/image_to_image/app.py
now/app/image_to_text/app.py
now/app/music_to_music/app.py
now/app/text_to_image/app.py
now/app/text_to_text/app.py
now/app/text_to_text_and_image/app.py
now/app/text_to_video/app.py
now/common/utils.py
now/constants.py
now/executor/autocomplete/Dockerfile
now/executor/autocomplete/config.yml
now/executor/autocomplete/executor.py
now/executor/autocomplete/requirements.txt
requirements-test.txt
tests/executor/autocomplete/test_integration.py
tests/executor/autocomplete/test_unit.py
tests/integration/test_end_to_end.py

fix: autocomplete

---

.github/workflows/ci.yml
deployment/bff/app/v1/routers/text2text.py
deployment/bff/app/v1/routers/txt2img.py
deployment/bff/app/v1/routers/txt2video.py
deployment/playground/playground.py
deployment/playground/src/search.py
docs/user-guides/production.md
now/app/base/app.py
now/app/image_to_image/app.py
now/app/image_to_text/app.py
now/app/music_to_music/app.py
now/app/text_to_image/app.py
now/app/text_to_text/app.py
now/app/text_to_text_and_image/app.py
now/app/text_to_video/app.py
now/common/utils.py
now/constants.py
now/executor/autocomplete/Dockerfile
now/executor/autocomplete/config.yml
now/executor/autocomplete/executor.py
now/executor/autocomplete/requirements.txt
requirements-test.txt
tests/executor/autocomplete/test_integration.py
tests/executor/autocomplete/test_unit.py
tests/integration/test_end_to_end.py

refactor: autocomplete

---

README.md
docs/index.md
docs/user-guides/input_format.md
now/app/base/app.py
now/app/image_to_image/app.py
now/app/image_to_text/app.py
now/app/music_to_music/app.py
now/app/text_to_image/app.py
now/app/text_to_text/app.py
now/app/text_to_video/app.py
now/common/options.py
now/constants.py
now/data_loading/data_loading.py

better explanation  for input format

docs: explain input format

---

deployment/bff/app/v1/routers/txt2video.py
now/constants.py

one of our older flows does not support the new BFF endpoint for search

fix: support older flow

---

.github/workflows/ci.yml
now/constants.py
now/executor/preprocessor/Dockerfile
now/executor/preprocessor/requirements-now.txt
now/executor/preprocessor/requirements.txt

refactor: preprocessor build time

---

deployment/bff/app/v1/routers/txt2video.py
now/constants.py
tests/executor/preprocessor/test_unit.py

The traversal path should not be on chunk chunk level in the current state. Later, we will remove access paths

fix: bff text to video

---

now/app/base/preprocess.py
now/constants.py
now/executor/abstract/base_indexer/base_indexer.py
tests/executor/indexer/base/test_base_executor.py
tests/integration/test_transform_docarray.py

The following issues are fixed:
- duplicates in curation
- new clip encoder address
- not ignore case for synonym
- test added

fix: different search term after curation

---

docs/_templates/sidebar/navigation.html
now/utils.py

Updating names to fit current product landscape
Signed-off-by: Alex C-G <alexcg@outlook.com>

fix: change all instances of jina hub to jina ai cloud

---

now/constants.py
now/executor/abstract/base_indexer/base_indexer.py
tests/executor/indexer/base/test_base_executor.py

instead of querying the filters during search, it happens when calling the curation endpoint leading to much better performance on query time
---

refactor: improve performance curation

---

now/app/text_to_video/app.py
now/app/text_to_video/flow-video-clip-high-performance.yml
now/run_backend.py

fixes the issue we currently have with the core/wolf when indexing larger datasets.
Instead of indexing the whole dataset at once, we break it into batches and introduced retries

fix: workaround core wolf

---

now/common/flow/flow-external-clip.yml
now/constants.py

Update the clip remote deployment and bump jina version for the external flow
---

fix: new remote deployment

---

now/cli/__init__.py
now/run_all_k8s.py

One level in the class run_k8s is removed to make the understanding easier
---

refactor: remove one level in call stack

---

now/common/detect_schema.py

expand user (~) in case of local data source

fix: expand user

---

now/cloud_manager.py
now/common/options.py

remove extra question -  jina-now is deployed already. 
We give the responsibility to the user

refactor: simplify dialog

---

now/constants.py
tests/unit/data_loading/test_data_loading.py

wrong app was selected when indexing gif

fix: gif in image app

---

now/common/options.py
now/utils.py

Fix English inconsistencies and old "JCloud" references
---

fix: grammar and naming

---

deployment/playground/src/search.py
now/constants.py

Fixes display of images in playground
---

fix: fix playground display blob

---

README.md
docs/user-guides/cli_api.md
docs/user-guides/input_format.md

This PR makes changes to the documentation, by updating the information and explanations on how users may upload their custom datasets for NOW applications.
---

docs: refactor input format explanation

---

deployment/playground/playground.py
now/constants.py

Closes https://github.com/jina-ai/now/issues/805
Playground screen
---

fix: handle new modality in playground

---

now/common/options.py

fix: index field

---

deployment/playground/playground.py
now/constants.py

Closes https://github.com/jina-ai/now/issues/808
`set` was producing a different sequence every time, that's why the order of search options was inconsistent. 
---

fix: order of search options

---

docs/user-guides/input_format.md

docs: add info about multi-modal documents

---

deployment/playground/Dockerfile
now/constants.py
now/deployment/k8s_playground-deployment.yml
tests/integration/test_end_to_end.py

closes https://github.com/jina-ai/now/issues/832 and https://github.com/jina-ai/now/issues/844
flow deletion was tested manually
---

refactor: save flow details before assertions

---

now/constants.py
now/executor/indexer/elastic/elastic_indexer.py
now/executor/indexer/elastic/es_converter.py
now/executor/indexer/elastic/es_query_building.py
tests/executor/indexer/elastic/test_es_converter.py

fix: small updates in elastic indexer

---

now/common/options.py
now/dialog.py
now/utils.py

raise a different exception if the intention is to ask the dialog again
---

fix: enable retry

---

deployment/bff/app/v1/routers/search.py
now/constants.py
tests/integration/offline_flow/test_offline_flow.py

search endpoint of bff in offline flow
multi-modal return values in bff

Test include bff in offline flow

---

now/common/options.py
now/dialog.py

It fixes a small bug introduced due to retry mechanism (my previous PR #868 ) for the dialog
---

Fix dialog broken

---

now/common/utils.py

we quickly run out of quota and it is expensive to have 15 replicas for each flow running on ci

ci: no high performance flow

---

deployment/bff/app/v1/routers/search.py
now/constants.py

refactor: deployment of bff

---

now/data_loading/data_loading.py

fix: add tags to docarrays

---

now/data_loading/data_loading.py

fix: move tag adding logic inside docarrays

---

now/cloud_manager.py

closes https://github.com/jina-ai/now/issues/651
---

fix: add space

---

README.md

closes https://github.com/jina-ai/now/issues/616
---

docs: add os requirements

---

now/common/detect_schema.py

closes https://github.com/jina-ai/now/issues/901
---

fix: speed up schema detection

---

deployment/playground/playground.py
deployment/playground/requirements.txt
deployment/playground/src/constants.py
now/constants.py

Closes https://github.com/jina-ai/now/issues/905
---

refactor: remove webcam

---

.github/workflows/cd.yml
.github/workflows/ci.yml
now/constants.py
now/executor/indexer/elastic/elastic_indexer.py

When there are no documents in the indexer, the '/list' endpoint throws an error.
---

fix: list endpoint when indexer is empty

---

deployment/playground/playground.py

fix: playground import

---

deployment/playground/playground.py
now/constants.py

I broke the cd and now have to make this fix

Fix playground import

---

deployment/playground/src/search.py
now/constants.py
tests/integration/cli/test_cli.py

- skip cli test since it is not deleting the flows
- remove log since it is slowing down the playground

refactor: cleanup

---

.github/workflows/update-durations.yml

the durations need to be updated from time to time to get the tests evenly distributed

test: update durations

---

requirements-test.txt
tests/conftest.py
tests/executor/autocomplete/test_integration.py
tests/executor/autocomplete/test_unit.py
tests/executor/preprocessor/test_integration.py
tests/executor/preprocessor/test_unit.py
tests/unit/apps/test_apps.py
tests/unit/apps/test_preprocessing.py

refactor: use mm docs in tests

---

now/constants.py
requirements.txt

chore: bump jcloud

---

deployment/bff/app/v1/routers/search.py
now/constants.py
now/data_loading/create_dataclass.py
now/data_loading/data_loading.py
now/data_loading/elasticsearch/data_extractor.py
now/executor/preprocessor/s3_download.py
tests/integration/local/test_end_to_end.py
tests/unit/test_dataclass.py

Closes #974 
- removed filter fields logic from dataclass creation and refactored other parts of the project accordingly
- added tag creation in es extractor
- combined `_add_tags_to_da` and `_get_da_with_index_fields`
Also, fixes https://github.com/jina-ai/now/issues/971
screenshot of a deployment
---

refactor: cleanup dataclass creation

---

.pre-commit-config.yaml
now/constants.py
now/executor/indexer/elastic/elastic_indexer.py

refactor: elastic update tags

---

now/common/options.py

fix: add slash to s3 path

---

tests/integration/remote/assertions.py
tests/integration/remote/test_e2e_s3_bucket.py
tests/unit/data_loading/test_data_loading.py

S3 bucket data has been changed. This PR adjusts tests to the changes. 
---

fix: s3 bucket tests

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/force-deploy-examples.yml
.github/workflows/update-durations.yml
now/common/options.py
now/now_dataclasses.py
now/utils.py
scripts/deploy_examples.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/local/conftest.py
tests/integration/remote/test_e2e_s3_bucket.py

Allowed AWS configure to automatically fill the credentials in both tests and CLI.
---

feat: use aws configure profile

---

now/constants.py
now/data_loading/data_loading.py
now/executor/gateway/bff/app/v1/models/shared.py
now/executor/gateway/bff/app/v1/routers/search.py
now/executor/indexer/elastic/es_converter.py
now/executor/indexer/elastic/es_query_building.py
now/utils.py
tests/unit/test_utils.py

fix: field name conflicting with Document attributes leads to error

---

now/constants.py
now/executor/gateway/playground/playground.py

At the moment, it is not possible to hit enter for search. It is fixed in this pr.
After this pr, it is possible to search by hitting enter.
Search button removed
[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://user-images.githubusercontent.com/11627845/218160018-031cc11b-d999-4233-beff-cab145ba7d4b.mov)

fix: search on enter

---

.pre-commit-config.yaml
scripts/aws-check-credentials.sh

bug: stabilize pre-commit hook

---

now/constants.py
now/executor/gateway/playground/playground.py

the survey can be removed since the playground is just for us developers

refactor: remove survey

---

scripts/deploy_examples.py

Fix demo aws config

---

scripts/deploy_examples.py

First, delete the flow before deploying a new one in the deploy_examples script
---

fix: first delete the flow

---

now/app/search_app/app.py
tests/integration/remote/assertions.py
tests/integration/remote/test_e2e_s3_bucket.py
tests/unit/data_loading/test_data_loading.py

Revert the serverless changes for preprocessor
---

fix: use replicas for preprocessor

---

now/app/search_app/app.py
now/constants.py
now/executor/indexer/elastic/elastic_indexer.py
now/executor/indexer/elastic/requirements.txt

we need to use the right volume for the elastic search deployment. Otherwise, it would not persist after a node drain

test: use right volume

---

now/app/search_app/app.py

documentation is wrong on the core. It should be 'kind' instead of 'type'

fix: kind ebs

---

scripts/prepare_laion_data.py

Closes https://github.com/jina-ai/now.private/issues/293
Pull original `laion400m` data uploaded by Jie;
Process each subset to match the multimodal docarray structure required by our project;
Aggregate each subset into one;
Push the aggregated data into the s3 bucket;
Created an app using a small subset
---

feat: script for preparing laion100m data

---

now/common/options.py
now/data_loading/create_dataclass.py
tests/unit/test_dataclass.py

Closes #1106, cf. output below during `data_loading`:
```
📄 Document: da49f57f5036794f71a6ae41c186c46f
└── 💠 Chunks
├── 📄 Document: ef04523a0b3cc22c023910e5f745eac4
│   ╭─────────────┬────────────────────────────────────────────────────────────────╮
│   │ Attribute   │ Value                                                          │
│   ├─────────────┼────────────────────────────────────────────────────────────────┤
│   │ parent_id   │ da49f57f5036794f71a6ae41c186c46f                               │
│   │ granularity │ 1                                                              │
│   │ mime_type   │ image/gif                                                      │
│   │ uri         │ s3://… │
│   │ modality    │ video                                                          │
│ …
```

fix: fix modality for s3

---

docs/user-guides/production.md
now/app/search_app/app.py

feat: specify shards and replicas for es-index-manager index creation

---

now/app/base/app.py
now/app/search_app/app.py
now/constants.py

fix: enable spot capacity

---

now/cli/__init__.py

This PR brings a dummy change to force a retrigger of the CD on the main branch.
---

fix: Force push

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Partly completes https://github.com/jina-ai/now.private/issues/313
Problem definition:
Uploading the coverage files to codecov was removed from CD in [this commit](https://github.com/jina-ai/now/commit/11a334196e5ca35c1777a3e1e324b7e633f65bd7), which is why the commit we have been comparing all of our PRs on is [this one](https://github.com/jina-ai/now/commit/ea7eab1633c95a8fbfbb4b14a87eb36a742b8b63), committed just before and last to run cd with codecov upload.
This PR simplifies the ci codecov logic and also adds the codecov upload back into the cd.
---

chore: fix codecov

---

now/data_loading/create_dataclass.py

fix: spelling correction for dummy pr

---

tests/integration/conftest.py

fix: naming cd flows

---

.github/workflows/ci.yml
now/constants.py
requirements.txt

chore: bump jcloud version

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/update-durations.yml
now/constants.py
scripts/prepare_laion_data.py
tests/integration/conftest.py
tests/integration/local/conftest.py
tests/integration/remote/test_e2e_s3_bucket.py

Closes https://github.com/jina-ai/now/issues/1148
---

refactor: hardcode s3 dataset paths

---

now/constants.py
now/executor/gateway/bff/app/settings.py
now/executor/gateway/bff/app/v1/routers/info.py
now/executor/gateway/bff/app/v1/routers/search.py
tests/conftest.py
tests/integration/offline_flow/test_offline_flow.py
tests/unit/bff/v1/routers/test_info.py
tests/unit/bff/v1/routers/test_search.py

Closes https://github.com/jina-ai/now/issues/1168
by mocking `get_user_input` functionality for the tests
---

fix: shared bff user input in tests

---

now/app/base/app.py
now/constants.py
requirements.txt

fix: custom dns for http

---

now/constants.py
now/data_loading/data_loading.py
now/executor/preprocessor/executor.py
now/executor/preprocessor/s3_download.py
now/now_dataclasses.py
now/run_backend.py
tests/conftest.py
tests/executor/preprocessor/test_unit.py
tests/integration/conftest.py
tests/integration/local/conftest.py
tests/unit/data_loading/elastic/test_elasticsearch.py
tests/unit/data_loading/test_data_loading.py

test: add preprocessor tests

---

now/common/detect_schema.py
tests/conftest.py
tests/executor/autocomplete/test_integration.py
tests/executor/autocomplete/test_unit.py

refactor: remove dup code

---

now/common/flow/flow-external-sbert.yml

update yaml. Deployment done already

fix: memory leak sbert

---

.github/workflows/cd.yml
.github/workflows/ci.yml
now/constants.py
now/executor/gateway/hubble_report.py

feat: add billing logging

---

now/client/__init__.py
requirements-test.txt
tests/unit/test_client.py

closes https://github.com/jina-ai/now.private/issues/341
---

test: add client coverage

---

now/app/base/app.py
now/constants.py

fix: add gateway labels
