- requirements_pip.txt
As mentioned in the issue #47, it seems that the dataset files have to re-created to overcome the latest docarray changes. However to avoid that, for now we will set the docarray version. Ticket to remain open for future implementation
> fix: set docarray version to avoid changes

- now/cli/__init__.py
I found that after fresh installation in a new environment, on calling `jina --help` and `streamlit --help` takes time for the first execution, however second onwards it is fast. Same behavior is observed with `jina-now`. I have moved the import statement inside func so that there's less delay on calling `jina-now --help` #56
> fix: move import inside func to make exec fast

- now/cloud_manager.py
Terminate the program execution when the kind fails to create cluster due to any issue and print the error as it is: #42
> fix: terminate when failed to create cluster

- README.md
Updated docs to reflect recommendation to install Jina NOW in a conda environment for Mac M1 users.
> docs: added m1 installation

- deployment/bff/requirements.txt
- deployment/playground/requirements.txt
- now/run_all_k8s.py
Protobuf errors occurs currently in bff and playground. Following https://discuss.streamlit.io/t/typeerror-descriptors-cannot-not-be-created-directly/25639/12 adding `protobuf~=3.19` resolves this.
> Fix protobuf version

- now/cloud_manager.py
- now/data_loading/data_loading.py
- now/deployment/flow.py
- now/dialog.py
- now/finetuning/run_finetuning.py
- now/hub/hub.py
- now/log/__init__.py
- now/log/log.py
- now/run_all_k8s.py
- now/run_backend.py
- now/run_bff_playground.py
This PR closes #230 by adding
- a decorator (`now.log.log.time_profiler`) to profile functions runtime
- an extension of `extended_yaspin` to show time needed for that spinner to finish
- decoration of known time-consuming functions with above decorator
- all time logging is in the format `HH:MM:SS.FSECFSEC`
With above decorator one can decorator any new function. As we typically use a spinner for time-consuming code block, the extension of `extended_yaspin` will log that time consumption.
An example output of the CI for `best-artworks` deployed `local`:
Output options of decorator are (let me know if you have other suggestions than the current one)
- `Time to execute now.cloud_manager.setup_cluster: (0:00:18.21)` (current one)
- `[now.cloud_manager.setup_cluster: 0:00:18.21]` …
> Add time profiling for CI

- now/run_all_k8s.py
- tests/integration/test_end_to_end.py
Currently, it was not possible for me to only delete the namespace when running `jina-now stop`.
```
if len(choices) == 0:
...
else:
questions = [
{
'type': 'list',
'name': 'cluster',
'message': 'Which cluster do you want to delete?',
'choices': choices,
}
]
cluster = maybe_prompt_user(questions, 'cluster', **kwargs)
if cluster == 'kind-jina-now':
...
elif 'wolf.jina.ai' in cluster:
...
else:
with yaspin_extended(
sigmap=sigmap, text=f"Remove jina NOW from {cluster}", color="green"
) as spinner:
cmd(f'{kwargs["kubectl_path"]} delete ns nowapi')
spinner.ok('💀')
cowsay.cow(f'nowapi namespace removed from {cluster}')
```
The namespace deletion branch is in the last `else` which can only reached when the users selects a choice other than 
a wolf cluster or the standard `kind-jina-now` …
> fix: now stop delete namespace

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- now_common/flow/flow-clip.yml
Team Wolf has developed a new feature that allows monitoring function for JCloud deployed Flow. This can be enrolled by setting `monitoring: true` in Flow YAML. Talked to @makram93, we decided to enable one and test it out.
> feat: enable monitoring for flow-clip

- now/deployment/deployment.py
- now/run_all_k8s.py
Instead of only retrieving the wolf flows whose ids are stored in cache, now we retrieve all alive flows when wanting to delete flows.
> feat: list all wolf deployments when asking to delete flows

- deployment/playground/playground.py
- now/constants.py
Even after logout app logs in with a different user account(as it is perceived) because the JWT cookies persist in the session and the app retrieves all session cookies. With this PR we only extract cookies of the current session, hence other JWT cookies will not be extracted
> fix: remove getting all cookies

- now/dialog.py
- now/utils.py
- requirements.txt
In this PR we update the requirements and make use of the latest version of `jina-hubble-sdk` which is the central library for auth across Jina ecosystem.
> Update JCloud and use latest jina auth

- .github/workflows/ci.yml
- .github/workflows/force-release.yml
This PR adds dispatch workflows to trigger the CD workflow of now.private whenever a new Jina NOW version is released. This is done to automate the process of keeping the `now_api` up to date.
> feat: trigger dispatch workflows

- tests/integration/test_end_to_end.py
Today, I had to delete a lot of ci flows again. I think the reason is that sometimes the tests are timing out due to errors in some executors. In that case, the flow is not deleted. In this pr, we set a timeout for the test itself to make sure the cleanup fixture is triggered.
> test: timeout

- .github/workflows/ci.yml
Setting `--verbose` when doing `jina hub push` may give more information for debugging.
> ci: enable hub push verbosity for more logs

- now/admin/update_api_keys.py
Since we are using replicas, the propagation of the API key can not be guaranteed. We increase the likelihood that all replicas will get a key by sending more requests.
Assume, we have 10 replicas and 100 requests of type `add_api_key`.
We assume that the probability of what replica is used is evenly distributed.
It means that the likelihood that a replica has an api_key is:
`1-(9/10)^100` ~ 1
> fix: add api keys

- now/utils.py
At the moment the program execution just crashes in case the email is not contained in the hubble response. Instead, we should print an error message and continue the execution
> fix: no email ignore error

- now/deployment/flow.py
- now/run_backend.py
- tests/integration/security/test_api_key.py
the other executors inherit from the security executor, so it is not needed alone
> refactor: remove security executor deployment

- deployment/playground/playground.py
- now/constants.py
When loading samples, if the link is not correct then it will throw HTTP error. Instead of that, catch the error silently and do not show the samples.
> fix: playground url inside try catch

- now/constants.py
- now_executors/NOWAnnLiteIndexer/executor.py
- tests/now_executors/NOWAnnLiteIndexer/test_executor.py
List endpoint currently returns the flat docs which is wrong when we have chunks of documents. This PR solves it by removing the duplicates and only returning single docs for all chunks of the same parent.
> fix: update list endpoint and test cases

- now/cli/__init__.py
- now/constants.py
Fixes the first part of https://github.com/jina-ai/now/issues/539
Multiprocessing imports the `__init__` module for each process, resulting in printing `Initialising Jina NOW` several times. It's fixed by moving print statement into the `cli()` function.
> fix: multiple initialisation prints

- requirements.txt
Bumping finetuner version, otherwise it doesn't work.
> chore: bump finetuner version

- now/admin/update_api_keys.py
- now/admin/update_email.py
- now/admin/utils.py
- now/constants.py
- now/deployment/deployment.py
- now/deployment/flow.py
- now/run_all_k8s.py
- tests/integration/security/test_api_key.py
- tests/integration/test_end_to_end.py
This PR refactors the jc_secret and removes all its occurrences. In the integration test, we still need to keep track of the deployed flow for post-cleanup. We cannot list all flows and deploy them as they may be in use in other parallel tests. 
This PR also solves #542
> Refactor remove jc secret

- .github/workflows/ci.yml
Due to how command line "plugins" work `jina hub --no-cache push` and `jina hub --no-cache push` turned out to be quite different.
For you to better understand this `jina --version hub ...` will always print jina version and quit.
In our case `--no-cache` was defined on `push` but not `hub`.
We'll see if we can get around this somehow.  
But let's fix your CI first.
> fix(ci): hub push no-cache flag

- pytest.ini
- tests/integration/test_end_to_end.py
This PR separates `local` and `remote` end-2-end tests so that they can be run in the operator github workflow
> test: separate remote and local tests

- now/common/options.py
- tests/executor/preprocessor/test_unit.py
- tests/unit/test_dialog.py
This PR solves the bug that users were able to input strings with special characters and spaces as an `app_name` causing an issue for flow creation. The `app_name` is now formatted after entering to remove any unwanted characters.
---
---
Note: this PR makes a small change to a test that was flaky, in order to make it deterministically pass. Created a follow up ticket #798 for a real solution.
> fix: remove unwanted chars from app name

- tests/conftest.py
- tests/unit/bff/v1/conftest.py
- put the image fixture one level up to make it accessible to other tests.
- elastic fixture should also work when not executing it from the root dir
> refactor: conftest

- now/common/detect_schema.py
- now/data_loading/data_loading.py
- now/utils.py
- tests/unit/test_detect_schema.py
- flattens the json files
- set all attributes without file ending to string
- give the user the opportunity to select index fields from all fields
- file type detection only based on value
before:
after:
> fix: show all fields for indexing

- now/common/options.py
Allow `All of the above` as an option in the filter fields
When there's only one filter field
When multiple filter fields
---
> fix: allow all as an options in filter

- now/app/search_app/app.py
- now/constants.py
- now/executor/indexer/elastic/elastic_indexer.py
- tests/conftest.py
- tests/executor/indexer/test_elastic_in_flow.py
- tests/executor/indexer/test_es_converter.py
- tests/executor/indexer/test_executor.py
- tests/integration/local/conftest.py
- tests/integration/local/test_end_to_end.py
- tests/integration/offline_flow/flow.py
- tests/integration/offline_flow/test_offline_flow.py
In this PR, the setup of elasticsearch in the cluster is removed. As such, the indexer no longer directly creates and configures the elasticsearch instance. Instead, this resource is provisioned by the `es-index-manager` (see [this repo](https://github.com/jina-ai/es-index-manager) for more info). The `es-index-manager` operator looks for the label `provision-index: "yes"` on our deployment in order to provision resources for it. This label should be found under the`spec.template.metadata.labels`, as shown below in the screenshot. If this label is not present, the operator will not create indices. When the deployment is cleaned up and removed, the operator will take note and also remove the index.
In the case of local integration tests, as well as offline flow tests, fixtures such as …
> feat: integrate es index manager

- now/app/base/app.py
- now/app/search_app/app.py
- now/constants.py
latest wolf update defaults to on-demand instances, but we should only use spot instances
> refactor: spot instances

- now/constants.py
- now/executor/gateway/bff/app/v1/routers/search.py
- now/executor/gateway/playground/playground.py
- tests/conftest.py
- tests/integration/offline_flow/test_offline_flow.py
- tests/integration/remote/assertions.py
- tests/integration/remote/test_e2e_docarray.py
- tests/integration/remote/test_e2e_elastic.py
- tests/integration/remote/test_e2e_local_folder.py
- tests/unit/bff/conftest.py
- tests/unit/bff/v1/routers/test_info.py
- tests/unit/bff/v1/routers/test_search.py
Previously, when defining semantic scores, one could not define query fields with arbitrary names. The API only accepted semantic scores defined with query fields `'text_0', 'text_1' ...` and `'image_0', 'image_1' ...`. However, the query field in the semantic scores should be allowed to be any string name, as long as it is **consistent** with the name defined in the `'name'` of the query. For example, one would expect that the following snippet works with query field name `'my_query_text'`:
```
import requests
HOST = "<my_host_url>"
request_body = {
'query': [{'name':'my_query_text', 'modality': 'text', 'value': 'test'}],
'semantic_scores': [('my_query_text', 'label', 'encoderclip', 1.0)]
}
response = requests.post('{HOST}/api/v1/search-app/search', json=request_body) …
```
> fix: update semantic scores based on dataclass fields of query

- now/constants.py
- requirements-test.txt
- requirements.txt
Fixes that installation from source without installing `requirements-test.txt` is causing an error.
---
> fix: fix pandas for compare flows

- now/constants.py
- now/executor/gateway/bff/app/settings.py
- now/executor/gateway/bff/app/v1/routers/info.py
- now/executor/gateway/bff/app/v1/routers/search.py
- tests/conftest.py
- tests/integration/offline_flow/test_offline_flow.py
- tests/unit/bff/conftest.py
- tests/unit/bff/v1/routers/test_info.py
- tests/unit/bff/v1/routers/test_search.py
Make user_input_in_bff global and initialize it in mocked client everytime so that the user_input.json is loaded properly with the correct values
---
> fix: user input bff

- .github/codecov.yml
- docs/user-guides/cli_api.md
- now/constants.py
- now/executor/gateway/bff/app/v1/models/search.py
- now/executor/gateway/bff/app/v1/routers/search.py
- now/executor/gateway/playground/playground.py
- now/executor/indexer/elastic/es_query_building.py
- tests/executor/indexer/test_elastic_in_flow.py
- tests/executor/indexer/test_es_query_building.py
- tests/executor/indexer/test_executor.py
- tests/integration/local/test_custom_da_with_tags.py
- tests/unit/bff/v1/routers/test_search.py
Enabling multiple filters sent in the search request. Slight change to the filter parameter, also updated the documentation for NOW and API documentation to reflect new format. 
Note that numerical and categorical filters now have different input fields in the playground: if a filter has numerical information (eg. price, size -> `float` or `int`), then we use a range slider with min + max values. If the filter has categorical information (eg. color, category -> `str`), then we use a multiselect field where multiple values can be selected.
As for the API request body with a filter, this is what it should look like:
```
{
"filters": {
"color": ["blue", "red"],
"price": {"lte": 100, "gte": 50}
},
"query": [
...
],
"create_temp_link": false,
"score_calculation": [
...
]
}
```
For more info on …
> feat: allow multiple filters
